name: ark_module_setup
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  app_tracking_transparency: ^2.0.2+4
  cached_network_image: ^3.1.0
  cloud_firestore: 3.1.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_analytics: ^9.1.9
  firebase_dynamic_links: ^4.2.5
  firebase_messaging: ^11.4.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  flutter_html: ^2.1.4
  flutter_inappwebview: ^5.4.4
  flutter_local_notifications: ^9.2.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  intl: ^0.17.0
  lottie: ^1.3.0
  mixpanel_flutter: ^1.5.1
  package_info: ^2.0.2
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  url_launcher: ^6.0.12
  path_provider: ^2.0.10
  sqflite: ^2.0.3+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
